# Generated by Django 2.2.10 on 2020-02-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DustInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.TextField()),
                ('dataTime', models.TextField()),
                ('pm25Value', models.TextField()),
                ('pm25Value24', models.TextField()),
                ('pm10Value', models.TextField()),
                ('pm10Value24', models.TextField()),
                ('o3Value', models.TextField()),
                ('no2Value', models.TextField()),
                ('so2Value', models.TextField()),
                ('khaiValue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('created_date', models.CharField(max_length=50)),
                ('newsimg', models.TextField()),
                ('newslink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaction', models.TextField()),
                ('sky', models.TextField()),
                ('tc', models.TextField()),
                ('tmin', models.TextField()),
                ('tmx', models.TextField()),
                ('timerelease', models.TextField()),
            ],
        ),
    ]
